version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cinerex_postgres
    restart: always
    ports:
      - '${port}:5432'
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_DB: ${name}
    volumes:
      - ./postgres:/var/lib/postgresql/data

